# Generated by Django 5.0.7 on 2024-07-25 02:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fornecedor",
            name="data",
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
