# Generated by Django 5.0.7 on 2024-07-25 02:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0002_fornecedor_data"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Fornecedor",
        ),
        migrations.AddField(
            model_name="produto",
            name="data",
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
