# Generated by Django 5.0.7 on 2024-07-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0003_delete_fornecedor_produto_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="tipo",
            field=models.CharField(default="ola", max_length=200),
        ),
        migrations.AlterField(
            model_name="produto",
            name="nome",
            field=models.TextField(),
        ),
    ]
