# Generated by Django 5.0.7 on 2024-07-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0004_produto_tipo_alter_produto_nome"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="tipo",
        ),
        migrations.AddField(
            model_name="produto",
            name="descricao",
            field=models.TextField(default="Descreva sobre seu produto"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="nome",
            field=models.CharField(max_length=20),
        ),
    ]
