# Generated by Django 5.0.7 on 2024-07-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0005_remove_produto_tipo_produto_descricao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="qunatidade",
            field=models.IntegerField(default=0),
        ),
    ]
