# Generated by Django 5.0.7 on 2024-07-25 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0006_produto_qunatidade"),
    ]

    operations = [
        migrations.RenameField(
            model_name="produto",
            old_name="qunatidade",
            new_name="quantidade",
        ),
    ]
